### ISSUE TITLE
`pnpm build` fails after commit bb855a2f8f1be70d1b1f739ed229bcd09b73f931

### ISSUE THREAD

**Issue by laanwj** [hzrd149/nostrudel#253]
i'm unable to do `pnpm build` after `pnpm install` on current master, i've bisected the problem to commit bb855a2f8f1be70d1b1f739ed229bcd09b73f931.

```
Lockfile is up to date, resolution step is skipped
Packages: -2
--

dependencies:
- applesauce-core 0.6.0
+ applesauce-core 0.0.0 <- ../applesauce/packages/core
- applesauce-react 0.6.0
+ applesauce-react 0.0.0 <- ../applesauce/packages/react
- applesauce-signer 0.6.0
+ applesauce-signer 0.0.0 <- ../applesauce/packages/signer

Done in 1.6s
```
```
> nostrudel@0.41.0 build /home/.../nostrudel
> tsc --project tsconfig.json && vite build "--outDir" "/home/www/..." "--emptyOutDir"
...
src/classes/accounts/account.ts:2:32 - error TS2307: Cannot find module 'applesauce-signer' or its corresponding type declarations.

2 import { Nip07Interface } from "applesauce-signer";
                                 ~~~~~~~~~~~~~~~~~~~

src/classes/accounts/amber-account.ts:1:38 - error TS2307: Cannot find module 'applesauce-signer' or its corresponding type declarations.

1 import { AmberClipboardSigner } from "applesauce-signer";
                                       ~~~~~~~~~~~~~~~~~~~

src/classes/accounts/extension-account.ts:1:32 - error TS2307: Cannot find module 'applesauce-signer' or its corresponding type declarations.

1 import { Nip07Interface } from "applesauce-signer";
                                 ~~~~~~~~~~~~~~~~~~~

src/classes/accounts/nsec-account.ts:2:30 - error TS2307: Cannot find module 'applesauce-signer' or its corresponding type declarations.

2 import { SimpleSigner } from "applesauce-signer";
                               ~~~~~~~~~~~~~~~~~~~

src/classes/accounts/serial-port-account.ts:1:34 - error TS2307: Cannot find module 'applesauce-signer' or its corresponding type declarations.
...
 ELIFECYCLE  Command failed with exit code 2
```
i have already tried to clean the tree, to no avail. Looks like it's dropping `applesauce` from the dependencies which isn't intentional.

Version:
```
$ pnpm -v
9.12.1
```
Let me know if you need any more info, i don't really know much about typescript build systems.

**Comment by laanwj** [comment]
thank you!

yes, the master version is unstable, i realize, but kind of important when trying to do development on top :smile:

> If you want to build it locally you can clone https://github.com/hzrd149/applesauce and link the packages locally. Ill try to write up some instructions in the readme at some point

OK that makes sense. Instructions would be very helpful, but i think i can figure it out with this.

**Comment by laanwj** [comment]
Can confirm the recent dependency change fixed the build flow.
